apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: abdaf48l2-go
  janus-idp.io/tekton: abdaf48l2-go
  backstage.io/kubernetes-id: abdaf48l2-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: abdaf48l2-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
